### ISSUE TITLE
Add actions

### ISSUE THREAD

**Issue by starchand** [parkerdan/SampleNavigation#2]
Thanks for this - really helpful!

I am still confused by redux - how do I add actions and new additional reducers to this? For example I've been trying to add on TabOneScreenOne a button that uses an global action to query an API and return the data in the mapStateToProps. Any chance you could do a quick mockup in this example?

Thanks!

**Comment by parkerdan** [comment]
It's just adding standard redux reducers and actions to add whatever you want.  I suggest watching these

https://egghead.io/courses/getting-started-with-redux

**Comment by starchand** [comment]
It's not standard though - I'm trying to bindActionCreators in TabBarNavigation.js:

```
<TabBar
        navigation={
          addNavigationHelpers({
            dispatch: dispatch,
            state: navigationState,
          })
        }
        actions={boundActionCreators}
      />
```

but the get dropped in `export const TabBar = TabNavigator(routeConfiguration,tabBarConfiguration)`

**Comment by parkerdan** [comment]
Once again, I suggest watching ALL of those videos
